### ISSUE TITLE
trailing whitespace

### ISSUE THREAD

**Issue by RaulCPena** [dracula/JupyterLab#1]
jupyterlab version 2.1.0
no whitespace added to last cell 
Would like to be able to bring last cell to the top

**Comment by RaulCPena** [comment]
Any update on correcting this issue. Still not able to scroll past last cell

**Comment by aricnappi** [comment]
I am having this issue as well. I love this theme but not being able to scroll past the last cell is becoming a problem.

**Comment by cfriedline** [comment]
I opened an issue for the same over here, but closed it finding this repo/one. Thanks for looking into it.

https://github.com/karosc/jupyterlab_dracula/issues/4

**Comment by cfriedline** [comment]
I recapitulated this theme using the latest cookiecutter and most of the settings from this repo. If anyone wants to try it out, it's here: https://github.com/cfriedline/theme-dracula

**Comment by karosc** [comment]
This should be corrected in the latest release:

![image](https://user-images.githubusercontent.com/36245370/105859243-4a4c4400-5fba-11eb-9608-b09c0a682efd.png)
