### ISSUE TITLE
Command palette selection not being highlighted

### ISSUE THREAD

**Issue by Per48edjes** [dracula/JupyterLab#18]
First and foremost, I ❤️ 🧛🏽 ! I was so excited to see it ported for use with Jupyter Lab. Just wanted to get one possible issue on the radar: the [command palette](https://jupyterlab.readthedocs.io/en/stable/user/commands.html) (<kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>C</kbd>) doesn't seem to highlight the selection when using the keyboard vs. when using the mouse (see examples below).

---

Here's my attempt using arrow keys:

![image](https://user-images.githubusercontent.com/9625484/126544925-ac1871a5-78f4-4233-a664-8539ec17a5ae.png)

Here's my attempt on mouseover:

![image](https://user-images.githubusercontent.com/9625484/126544961-f09e9ad3-1893-403d-aec1-10f586cecf6a.png)

**NB**: I'm still somewhat green when it comes to tweaking Jupyter Lab settings, so feel free to close this if this isn't a Dracula-specific issue.

**Comment by karosc** [comment]
This appears to be resolved in v0.2.0
