### ISSUE TITLE
Status bar below disappeared

### ISSUE THREAD

**Issue by ytdHuang** [dracula/JupyterLab#27]
My jupyterlab's version is : 3.2.9

In default themes (e.g. JupyterLab Dark), there exist a status bar below the jupyterlab UI, as shown in the figure.
But the status bar disappeared when i switch to dracula theme.
Anyone knows what happened or how to fix it ?

![image](https://user-images.githubusercontent.com/44385685/164895877-30dc3422-b00d-48aa-833f-aa44b403bb87.png)

**Comment by quarkquartet** [comment]
Same here/

**Comment by karosc** [comment]
Resolved in #39
