### ISSUE TITLE
Reduced whitespace before and after lines

### ISSUE THREAD

**Issue by setu4993** [dracula/JupyterLab#3]
Thanks for creating and maintaining this theme!

Noticing a minor issue with the whitespace rendering before and after in every cell. Attaching the default dark theme and this theme's output for the same cell.
Dracula theme (compressed line spacing):
<img width="1209" alt="Screen Shot 2020-05-25 at 11 58 54 PM" src="https://user-images.githubusercontent.com/1833708/82870215-6efc9300-9ee4-11ea-8769-9d54f1417855.png">

JupyterLab dark theme (more 'correct' line spacing):
<img width="1223" alt="Screen Shot 2020-05-25 at 11 59 17 PM" src="https://user-images.githubusercontent.com/1833708/82870216-6f952980-9ee4-11ea-827f-f3bfad9961cc.png">

Thanks, again, @karosc.

**Comment by karosc** [comment]
Seems to be fixed by #2
