### ISSUE TITLE
Checkmarks not visible in menus

### ISSUE THREAD

**Issue by ajdajd** [dracula/JupyterLab#4]
Here's a side-by-side comparison with Jupyterlab Dark:
![Screenshot from 2020-05-31 00-10-48](https://user-images.githubusercontent.com/13794421/83333503-4a812c00-a2d3-11ea-8996-2ed187ffc43d.png)

**Comment by karosc** [comment]
checkmarks are back! 

![image](https://user-images.githubusercontent.com/36245370/105859468-8da6b280-5fba-11eb-9d9e-1ea8c959ef85.png)
