### ISSUE TITLE
Commented text blends in with the selection/highlighting color

### ISSUE THREAD

**Issue by NicholasTuttle** [dracula/JupyterLab#5]
Hello,

It appears that the same color is being used for both the selection/highlighting and the font color for commented text.  Please check my attachment. These are two identical cells. When I try to selected the commented text, you can't tell what you're selecting.

Nick Tuttle

![Capture8](https://user-images.githubusercontent.com/42939286/85285764-78cfd280-b45f-11ea-8f7a-b38c12de0a9b.PNG)

**Comment by 7kemZmani** [comment]
there's a [PR ](https://github.com/dracula/jupyterlab/pull/6#issue-444287660)that fixes this issue

**Comment by karosc** [comment]
fixed by #6
