### ISSUE TITLE
Version not compatible

### ISSUE THREAD

**Issue by baron-digit** [dracula/JupyterLab#7]
Hi, would you mind to update to newer JupyterLab versions?

Conflicting Dependencies:
JupyterLab              Extension      Package
>=3.0.2 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/application
>=3.0.2 <3.1.0          >=2.0.0 <3.0.0 @jupyterlab/apputils
See the log file for details:  /tmp/jupyterlab-debug-7x_uqbor.log

I love dracula :-)

**Comment by ruslaniv** [comment]
Same here, and I love this theme.

**Comment by karosc** [comment]
fixed by #9 install with `pip install JLDracula`
